# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20160130_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='image', max_length=100),
            preserve_default=False,
        ),
    ]
